name: 🚧 Integration
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v4.1.0
        name: Install pnpm
        with:
          version: 8
      - uses: actions/setup-node@main
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm run test

  format:
    name: 💅 Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v4.1.0
        name: Install pnpm
        with:
          version: 8
      - uses: actions/setup-node@main
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm prettier --check .

  nextjs:
    name: ⚛️ NextJS application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v4.1.0
        name: Install pnpm
        with:
          version: 8
      - uses: actions/setup-node@main
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm build
